name: ci

on:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master

      - run: npm ci
      - run: npm test
      - run: npm run build

      - name: Coverage
        uses: codecov/codecov-action@v2
