name: ci

on:
  push:
    branches:
      - actions-testing
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
      fail-fast: true

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master

      - run: npm ci

      - name: Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          directory: ./packages/module/coverage
