name: ci

on:
  push:
    branches:
      - dev

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
      fail-fast: true

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@master

      - run: npm ci

      - name: Tests
        run: yarn jest

      - name: Coverage
        uses: codecov/codecov-action@v2
